ars/teachers/urls.py
from django.conf.urls import include, url

from . import views


urlpatterns = [
    url(r'^$', views.ListTeacherView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailTeacherView.as_view(), name='detail'),
]

mooc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from ars.subjects.views import ListSubjectView


urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),

    url(r'^$', view=ListSubjectView.as_view(), name='home'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
    
    url(r'^admin/', include('ars.admin.urls', namespace='admin')),
    url(r'^teachers/', include('ars.teachers.urls', namespace='teachers')),
    url(r'^students/', include('ars.students.urls', namespace='students')),
    url(r'^subjects/', include('ars.subjects.urls', namespace='subjects')),
    url(r'^about-us/', include('ars.about.urls', namespace='about')),
    url(r'^contact/', include('ars.contact.urls', namespace='contact')),
    url(r'^blog/', include('ars.blog.urls', namespace='blog')),
    url(r'^category/', include('ars.categories.urls', namespace='category')),
    url(r'^comment/', include('ars.comments.urls', namespace='comment')),
]

ars/teachers/models.py
from django.db import models
from django.conf import settings

from ars.core.models import UserProfile


class Teacher(models.Model):
    profile = models.OneToOneField(UserProfile,
                                default=None, related_name='teacher')

    class Meta:
        db_table = 'teacher'

    def __str__(self):
        return 'Teacher {}'.format(self.name)

    @property
    def username(self):
        return self.profile.user.username

    @property
    def avatar(self):
        if self.profile.avatar:
            return self.profile.avatar.url
        return None

ars/teachers/views.py
from django.views.generic import DetailView, ListView

from ars.core.views import BaseView
from ars.teachers.models import Teacher


class DetailTeacherView(BaseView, DetailView):
    model = Teacher
    template_name = 'teachers/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        info = {
            'info': {
                'title': self.object.username,
            },
            'page_title': self.object.username,
        }
        context.update(info)
        return context


class ListTeacherView(BaseView, ListView):
    model = Teacher
    template_name = 'teachers/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        info = {
            'info': {
                'title': 'Teachers',
            },
            'page_title': 'Teachers',
        }
        context.update(info)
        return context

templates/teachers/detail.html
{% extends 'layout/base.html' %}
{% load staticfiles %}

{% block sidebar %}{% endblock %}

{% block content %}{% endblock %}


		<!-- ========== CONTENT START ========== -->
{% block precontent %}

		<section id="content">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
                        <img src="{{ teacher.avatar }}" alt="{{ teacher.username }}" class="img-responsive" />
					</div>
					<div class="col-sm-6">
                        <h1>{{ teacher.username }}</h1>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu tellus ipsum. Nunc maximus sapien ac dui vulputate tincidunt. Morbi luctus nisi vel suscipit volutpat. Donec vitae auctor nisl. Ut malesuada felis in erat rutrum ultrices. Fusce iaculis ornare nunc rutrum ornare. Proin ut placerat enim, vel venenatis urna. Phasellus sed diam tincidunt mauris malesuada mattis et in nisl. Quisque massa eros, molestie at mi eget, aliquam tristique eros. Nullam aliquet placerat magna ut eleifend. Phasellus iaculis tristique laoreet.</p>
						<ul>
							<li>Fusce iaculis ornare nunc rutrum ornare.</li>
							<li>Proin ut placerat enim, vel venenatis urna.</li>
							<li>Phasellus sed diam tincidunt mauris malesuada mattis et in nisl.</li>
							<li>Quisque massa eros, molestie at mi eget, aliquam tristique eros.</li>
							<li>Nullam aliquet placerat magna ut eleifend.</li>
							<li>Phasellus iaculis tristique laoreet.</li>
						</ul>
					</div>
				</div>
			</div>
		</section>

		<!-- ========== CONTENT END ========== -->

		<!-- ========== REVIEWS START ========== -->

		<section id="teachers-reviews">
			<div class="tint"></div>
			<div class="container">
				<div class="row">
					<div class="col-sm-12 text-center" data-scroll-reveal>

						<!-- OWL CAROUSEL START -->
						<div class="owl-carousel">
							
							<div class="item">
								<blockquote>Donec varius ante in turpis faucibus sagittis. Vestibulum lacinia ante eget fringilla lobortis. Nunc sollicitudin, arcu at fringilla varius, turpis dui venenatis augue, at adipiscing ante ipsum vel leo. In a sem sit amet mi condimentum semper. Nulla eleifend convallis gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec blandit erat eu suscipit porttitor. Sed vestibulum mauris sit amet eros feugiat egestas. Ut rhoncus imperdiet est eget ullamcorper. Fusce at orci sed augue aliquam malesuada. <small>Sally Peterson, Student</small></blockquote>
							</div>
							
							<div class="item">
								<blockquote>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam semper consectetur nunc ac pretium. Nullam vel lectus non augue imperdiet porta. Proin commodo malesuada faucibus. Integer at lacinia lacus. Vestibulum dignissim imperdiet est vel ornare. Sed vehicula luctus massa, sit amet porta purus feugiat a. Cras tincidunt neque vitae enim pellentesque, nec congue mauris suscipit. Praesent sit amet odio lacus. <small>Malcolm Carr, Student</small></blockquote>
							</div>
							
							<div class="item">
								<blockquote>Integer faucibus orci eu lorem vulputate, non semper odio consectetur. Phasellus eu commodo lectus, interdum molestie nunc. Maecenas aliquet sagittis elementum. Nulla lobortis diam nisl, id consectetur nunc faucibus viverra. Donec vel porta augue, eget accumsan lorem. Sed dictum consequat ipsum eget porta. Donec imperdiet dolor at ante interdum, sed viverra orci iaculis. Donec vestibulum nulla at tortor molestie, vel convallis neque vestibulum. Phasellus luctus purus ut tincidunt imperdiet. <small>Antonia Owen, Student</small></blockquote>
							</div>
							
							<div class="item">
								<blockquote>Vestibulum viverra dolor lorem, vitae ornare velit facilisis eget. Phasellus ornare, mauris id interdum cursus, velit libero dictum dolor, a vehicula lacus enim id tortor. Vestibulum faucibus nec elit id iaculis. Aenean lorem ante, pretium ac iaculis non, tincidunt in quam. Nunc lobortis dictum dui. Pellentesque sagittis luctus posuere. Sed suscipit mi vitae orci accumsan, ut imperdiet odio molestie. <small>Jared Murray, Student</small></blockquote>
							</div>
							
						</div>
						<!-- OWL CAROUSEL END -->

					</div>
				</div>
			</div>
		</section>

		<!-- ========== REVIEWS END ========== -->

		<!-- ========== SKILLS START ========== -->

		<section id="skills">
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<h2>John's key skills</h2>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-6">
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu tellus ipsum. Nunc maximus sapien ac dui vulputate tincidunt. Morbi luctus nisi vel suscipit volutpat. Donec vitae auctor nisl. Ut malesuada felis in erat rutrum ultrices. Fusce iaculis ornare nunc rutrum ornare. Proin ut placerat enim, vel venenatis urna. Phasellus sed diam tincidunt mauris malesuada mattis et in nisl. Quisque massa eros, molestie at mi eget, aliquam tristique eros. Nullam aliquet placerat magna ut eleifend. Phasellus iaculis tristique laoreet.Donec vitae auctor nisl. Ut malesuada felis in erat rutrum ultrices. Fusce iaculis ornare nunc rutrum ornare. Proin ut placerat enim, vel venenatis urna. Phasellus sed diam tincidunt mauris malesuada mattis et in nisl. Quisque massa eros, molestie at mi eget, aliquam tristique eros.</p>
					</div>
					<div class="col-sm-6">
						<div class="progress">
							<div class="progress-bar" role="progressbar" data-transitiongoal="90">
								<span class="pull-left">Progresssive Web Design</span>
								<span class="pull-right">90%</span>
							</div>
						</div>
						<div class="progress">
							<div class="progress-bar" role="progressbar" data-transitiongoal="100">
								<span class="pull-left">HTML5</span>
								<span class="pull-right">100%</span>
							</div>
						</div>
						<div class="progress">
							<div class="progress-bar" role="progressbar" data-transitiongoal="80">
								<span class="pull-left">CSS3</span>
								<span class="pull-right">80%</span>
							</div>
						</div>
						<div class="progress">
							<div class="progress-bar" role="progressbar" data-transitiongoal="70">
								<span class="pull-left">jQuery</span>
								<span class="pull-right">70%</span>
							</div>
						</div>
						<div class="progress">
							<div class="progress-bar" role="progressbar" data-transitiongoal="80">
								<span class="pull-left">Online Marketing</span>
								<span class="pull-right">80%</span>
							</div>
						</div>
						<div class="progress">
							<div class="progress-bar" role="progressbar" data-transitiongoal="90">
								<span class="pull-left">SEO</span>
								<span class="pull-right">90%</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

{% endblock precontent %}
		<!-- ========== SKILLS END ========== -->

		<!-- ========== RELATED COURSES START ========== -->
        {% block related_subjects %}

		<section id="featured-posts" class="alt-background">
			<div class="container">
				
				<h2 class="text-center carousel-title">
					Related Courses
					<a href="#">View All Courses</a>
				</h2>

				<!-- OWL CAROUSEL START -->
				<div class="owl-carousel">
					
					<div class="item">
                        <a href="#"><img src="{% static 'frontend/images/course01.jpg' %}" alt="" class="img-responsive" /></a>
						<h3><a href="#">Creative Website Design	and Development</a></h3>
						<div class="meta">
							<p><a href="#">by John Doe</a></p>
							<p><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></p>
						</div>
						<div class="price">$39.90</div>
					</div>
					
					<div class="item">
                        <a href="#"><img src="{% static 'frontend/images/course02.jpg' %}" alt="" class="img-responsive" /></a>
						<h3><a href="#">Introducing to Digital Photography</a></h3>
						<div class="meta">
							<p><a href="#">by John Doe</a></p>
							<p><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></p>
						</div>
						<div class="price">$29.90</div>
					</div>
					
					<div class="item">
                        <a href="#"><img src="{% static 'frontend/images/course03.jpg' %}" alt="" class="img-responsive" /></a>
						<h3><a href="#">Adobe Illustrator and Vector Design Basics</a></h3>
						<div class="meta">
							<p><a href="#">by John Doe</a></p>
							<p><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></p>
						</div>
						<div class="price">$34.90</div>
					</div>
					
					<div class="item">
                        <a href="#"><img src="{% static 'frontend/images/course04.jpg' %}" alt="" class="img-responsive" /></a>
						<h3><a href="#">Introduction to Search Engine Optimisation</a></h3>
						<div class="meta">
							<p><a href="#">by John Doe</a></p>
							<p><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></p>
						</div>
						<div class="price">$27.90</div>
					</div>

				</div>
				<!-- OWL CAROUSEL END -->

			</div>
		</section>

        {% endblock related_subjects %}
		<!-- ========== RELATED COURSES END ========== -->

templates/teachers/list.html
{% extends 'layout/base.html' %}
{% load staticfiles %}

{% block related_subjects %}
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block content %}
{% endblock content %}

<!-- ========== CONTENT START ========== -->
{% block precontent %}

<section id="content">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="video-wrapper">
                    <iframe width="853" height="480" src="http://www.youtube.com/embed/L2LNK2MW_xQ" allowfullscreen></iframe>
                </div>
            </div>
            <div class="col-sm-6">
                <h1>Meet our staff</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu tellus ipsum. Nunc maximus sapien ac dui vulputate tincidunt. Morbi luctus nisi vel suscipit volutpat. Donec vitae auctor nisl. Ut malesuada felis in erat rutrum ultrices. Fusce iaculis ornare nunc rutrum ornare. Proin ut placerat enim, vel venenatis urna. Phasellus sed diam tincidunt mauris malesuada mattis et in nisl. Quisque massa eros, molestie at mi eget, aliquam tristique eros. Nullam aliquet placerat magna ut eleifend. Phasellus iaculis tristique laoreet.</p>
                <ul>
                    <li>Fusce iaculis ornare nunc rutrum ornare.</li>
                    <li>Proin ut placerat enim, vel venenatis urna.</li>
                    <li>Phasellus sed diam tincidunt mauris malesuada mattis et in nisl.</li>
                    <li>Quisque massa eros, molestie at mi eget, aliquam tristique eros.</li>
                    <li>Nullam aliquet placerat magna ut eleifend.</li>
                    <li>Phasellus iaculis tristique laoreet.</li>
                </ul>
            </div>
        </div>
    </div>
</section>

<!-- ========== CONTENT END ========== -->

<!-- ========== TEACHERS START ========== -->

<section id="teachers" class="alt-background">
    <div class="container">
        
        <h2>Teachers</h2>

        <ul class="teachers">
            
            {% for teacher in teacher_list %}
            <li class="col-lg-3 col-md-4 col-sm-6">
                <img src="{{ teacher.avatar }}" alt="No image" class="img-responsive" />
                <div class="description">
                    <h3>{{ teacher.username }}</h3>
                    <p>Non ipsum vulputate condimentum eu id tellus. Praesent commodo arcu quis rhoncus porttitor.</p>
                    <a href="{% url 'teachers:detail' teacher.pk %}">Read More <i class="fa fa-angle-right"></i></a>
                </div>
            </li>
            {% endfor %}

        </ul>

    </div>
</section>

<!-- ========== TEACHERS END ========== -->

<!-- ========== SKILLS START ========== -->

<section id="skills">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>Our key skills</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu tellus ipsum. Nunc maximus sapien ac dui vulputate tincidunt. Morbi luctus nisi vel suscipit volutpat. Donec vitae auctor nisl. Ut malesuada felis in erat rutrum ultrices. Fusce iaculis ornare nunc rutrum ornare. Proin ut placerat enim, vel venenatis urna. Phasellus sed diam tincidunt mauris malesuada mattis et in nisl. Quisque massa eros, molestie at mi eget, aliquam tristique eros. Nullam aliquet placerat magna ut eleifend. Phasellus iaculis tristique laoreet.Donec vitae auctor nisl. Ut malesuada felis in erat rutrum ultrices. Fusce iaculis ornare nunc rutrum ornare. Proin ut placerat enim, vel venenatis urna. Phasellus sed diam tincidunt mauris malesuada mattis et in nisl. Quisque massa eros, molestie at mi eget, aliquam tristique eros.</p>
            </div>
            <div class="col-sm-6">
                <div class="progress">
                    <div class="progress-bar" role="progressbar" data-transitiongoal="90">
                        <span class="pull-left">Progresssive Web Design</span>
                        <span class="pull-right">90%</span>
                    </div>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" data-transitiongoal="100">
                        <span class="pull-left">HTML5</span>
                        <span class="pull-right">100%</span>
                    </div>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" data-transitiongoal="80">
                        <span class="pull-left">CSS3</span>
                        <span class="pull-right">80%</span>
                    </div>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" data-transitiongoal="70">
                        <span class="pull-left">jQuery</span>
                        <span class="pull-right">70%</span>
                    </div>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" data-transitiongoal="80">
                        <span class="pull-left">Online Marketing</span>
                        <span class="pull-right">80%</span>
                    </div>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" data-transitiongoal="90">
                        <span class="pull-left">SEO</span>
                        <span class="pull-right">90%</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- ========== SKILLS END ========== -->
{% endblock precontent %}