ars/subjects/urls.py
from django.conf.urls import include, url

from . import views


urlpatterns = [
    url(r'^$', view=views.ListSubjectView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', view=views.DetailSubjectView.as_view(), name='detail'),
    url(r'^enroll/$', view=views.EnrollSubjectView.as_view(), name='enroll'),
]

mooc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from ars.subjects.views import ListSubjectView


urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),

    url(r'^$', view=ListSubjectView.as_view(), name='home'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
    
    url(r'^admin/', include('ars.admin.urls', namespace='admin')),
    url(r'^teachers/', include('ars.teachers.urls', namespace='teachers')),
    url(r'^students/', include('ars.students.urls', namespace='students')),
    url(r'^subjects/', include('ars.subjects.urls', namespace='subjects')),
    url(r'^about-us/', include('ars.about.urls', namespace='about')),
    url(r'^contact/', include('ars.contact.urls', namespace='contact')),
    url(r'^blog/', include('ars.blog.urls', namespace='blog')),
    url(r'^category/', include('ars.categories.urls', namespace='category')),
    url(r'^comment/', include('ars.comments.urls', namespace='comment')),
]

ars/subjects/models.py
from django.db import models
from django.conf import settings

from ars.categories.models import Category
from ars.courses.models import Course
from ars.students.models import Student
from ars.core.models import Describable, Timestampable


class Subject(Describable, Timestampable):
    course = models.ForeignKey(Course)
    categories = models.ManyToManyField(Category, db_table="category_subject", related_name='subjects')
    slug = models.SlugField(max_length=255)
    image = models.ImageField(upload_to=settings.SUBJECT_DIR, max_length=255, default='', blank=False)

    class Meta:
        verbose_name = "Subject"
        verbose_name_plural = "Subjects"
        db_table = 'subject'

    def get_image_url(self):
        if self.image:
            return self.image.url
        return ''

    def __str__(self):
        return self.name

    @property
    def latest_session(self):
        try:
            session = self.sessions.order_by('-id')[0]
        except:
            session = None
        return session


class Session(models.Model):
    subject = models.ForeignKey(Subject, related_name='sessions')
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    class Meta:
        verbose_name = "Session"
        verbose_name_plural = "Sessions"
        db_table = 'session'

    def __str__(self):
        return '{} - {}'.format(self.start_date, self.end_date)
    
class Task(Describable):
    session = models.ForeignKey(Session, related_name='tasks')
    slug = models.SlugField(max_length=255)
    content = models.TextField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    class Meta:
        verbose_name = "Task"
        verbose_name_plural = "Tasks"
        db_table = 'task'

    def __str__(self):
        return 'Task {}'.format(self.name)
    
    @property
    def is_published(self):
        return True

class Enroll(Timestampable):
    session = models.ForeignKey(Session, related_name='enrolls')
    student = models.ForeignKey(Student)

    class Meta:
        verbose_name = "Enroll"
        verbose_name_plural = "Enrolls"
        db_table = 'enroll'

    def __str__(self):
        return 'Student {} enrolled subject {}, start on {}'.format(
                                self.profile.user.username,
                                self.session.subject.name,
                                self.session.start_date)

ars/subjects/views.py
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, View, FormView
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden

from ars.subjects.models import Subject
from ars.core.views import LoginRequiredMixin, BaseView, StudentRequiredMixin
from ars.subjects.models import Enroll
from ars.reviews.forms import ReviewSubjectForm
from ars.reviews.models import Review

class ListSubjectView(BaseView, ListView):
    model = Subject
    template_name = 'subjects/index.html'
    paginate_by = 6

    def get_queryset(self):
        return Subject.objects.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        info = {
            'info': {
                'title': 'Subjects List',
                },
            'page_title': 'Subjects List',
        }
        context.update(info)
        return context


class DetailSubjectMixin(object):
    model = Subject
    template_name = 'subjects/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if hasattr(self.request.user, 'profile') and \
           hasattr(self.request.user.profile, 'student'):
            student = self.request.user.profile.student
            has_reviewed = Review.objects.filter(
                    student=student, subject=self.object).exists()
            if self.object.latest_session is not None:
                has_enrolled = self.object.latest_session.enrolls.filter(student=student).exists()
            else:
                has_enrolled = False
        else:
            has_reviewed = False
            has_enrolled = False
        

        if self.object.latest_session is not None:
            context['num_enrollers'] = self.object.latest_session.enrolls.count()

        info = {
            'info': {
                'title': 'Subject Detail',
                },
            'page_title': 'Subject',
        }
        context.update(info)
        context['has_reviewed'] = has_reviewed
        context['has_enrolled'] = has_enrolled
        return context
    

class DisplaySubjectView(DetailSubjectMixin, BaseView, DetailView):
    pass


class ReviewSubjectView(DetailSubjectMixin, BaseView, SingleObjectMixin, FormView):
    form_class = ReviewSubjectForm
    
    def get_success_url(self):
        return reverse_lazy('subjects:detail', kwargs={'pk': self.object.pk})
    
    def post(self, request, *args, **kwargs):

        if not request.user.is_authenticated():
            return HttpResponseRedirect(reverse('students:login'))

        if request.user.profile.is_teacher:
            return HttpResponseForbidden('You are a teacher, you cannot review')

        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.student = self.request.user.profile.student
        form.instance.subject = self.object
        form.save()
        return HttpResponseRedirect(self.get_success_url())


class DetailSubjectView(View):

    def get(self, request, *args, **kwargs):
        view = DisplaySubjectView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = ReviewSubjectView.as_view()
        return view(request, *args, **kwargs)


class EnrollSubjectView(StudentRequiredMixin, CreateView):
    model = Enroll
    fields = ['session']

    def get(self, request, *args, **kwargs):
        return HttpResponse()

    def get_success_url(self):
        return reverse('subjects:detail',
                    kwargs={'pk': self.object.session.subject.pk})
    
    def form_valid(self, form):
        form.instance.student = self.request.user.profile.student
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())

templates/subjects/index.html
{% extends 'layout/base.html' %}
{% load staticfiles %}

{% block related_subjects %}{% endblock %}

{% block content %}
    <!-- ==== COURSES START == -->
    <div class="col-sm-8">
        <div class="courses">
            {% for subject in object_list %}
            <!-- Course Start -->
            <div class="course row" data-scroll-reveal>
                <div class="col-sm-4">
                    <a href="{% url 'subjects:detail' subject.pk %}"><img src="{{ subject.image.url }}" alt="" class="img-responsive" /></a>
                </div>
                <div class="col-sm-8">
                    <div class="row">
                        <div class="col-md-9 col-sm-8">
                            <h3><a href="{% url 'subjects:detail' subject.pk %}">{{ subject.name }}</a></h3>
                            <div class="meta">
                                <span><i class="fa fa-user"></i><a href="{% url 'teachers:detail' subject.course.creator.pk %}">{{ subject.course.creator.profile.user.username }}</a></span>
                                <span><i class="fa fa-file-text"></i>4 Lessons</span>
                                <span><i class="fa fa-folder"></i>
                                    {% for category in subject.categories.all %}
                                    <a href="{% url 'category:index' category.pk %}">{{ category }}</a>,&nbsp;
                                    {% endfor %}
                                </span>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-4 price"></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <p style="text-align: justify;">{{ subject.description|truncatewords:50 }}<br>
                                <a href="{% url 'subjects:detail' subject.pk %}">Read more <i class="fa fa-angle-right"></i></a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <hr>
                </div>
            </div>
            <!-- Course End -->
            {% endfor %} {# for object_list #}
            {% if is_paginated %}
            <!-- Pagination Start -->
            <div class="row" data-scroll-reveal>
                <div class="col-sm-6">
                    <a class="btn btn-primary lesson-prev {{ page_obj.has_previous|yesno:',disabled' }}" href="?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number}}{% else %}{{ page_obj.number }}{% endif %}"><i class="fa fa-caret-left"></i> &nbsp; Previous</a>
                </div>
                <div class="col-sm-6 text-right">
                    <a class="btn btn-primary lesson-next {{ page_obj.has_next|yesno:',disabled' }}" href="?page={% if page_obj.has_next %}{{ page_obj.next_page_number}}{% else %}{{ page_obj.number }}{% endif %}">Next &nbsp; <i class="fa fa-caret-right"></i></a>
                </div>
            </div>
            <!-- Pagination End -->
            {% endif %}
        </div>
    </div>
    <!-- ==== COURSES END == -->
{% endblock content %}