ars/blog/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', view=views.BlogView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/$', views.BlogDetailView.as_view(), name='detail'),
]

ars/categories/urls.py
from django.conf.urls import include, url

from . import views


urlpatterns = [
    url(r'^(?P<pk>[0-9]+)$', view=views.CategoriesView.as_view(), name='index'),
]

mooc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from ars.subjects.views import ListSubjectView


urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),

    url(r'^$', view=ListSubjectView.as_view(), name='home'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
    
    url(r'^admin/', include('ars.admin.urls', namespace='admin')),
    url(r'^teachers/', include('ars.teachers.urls', namespace='teachers')),
    url(r'^students/', include('ars.students.urls', namespace='students')),
    url(r'^subjects/', include('ars.subjects.urls', namespace='subjects')),
    url(r'^about-us/', include('ars.about.urls', namespace='about')),
    url(r'^contact/', include('ars.contact.urls', namespace='contact')),
    url(r'^blog/', include('ars.blog.urls', namespace='blog')),
    url(r'^category/', include('ars.categories.urls', namespace='category')),
    url(r'^comment/', include('ars.comments.urls', namespace='comment')),
]

ars/categories/models.py
from django.db import models

from ars.core.models import Timestampable, Describable


class Category(Timestampable, Describable):

    class Meta:
        db_table = 'category'

    def __str__(self):
        return self.name

ars/categories/views.py
from django.views.generic import ListView

from ars.subjects.models import Subject
from ars.categories.models import Category
from ars.core.views import BaseView

class CategoriesView(BaseView, ListView):
    model = Subject
    template_name = 'categories/index.html'
    # paginate_by = 6
    context_object_name = 'list_subject'

    def get_queryset(self):
        return Subject.objects.filter(categories__id=self.kwargs['pk']).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        info = {
            'info': {
                'title': Category.objects.get(id=self.kwargs['pk']).name,
                },
            'page_title': Category.objects.get(id=self.kwargs['pk']).name,
        }
        context.update(info)
        return context

templates/categories/index.html
{% extends 'layout/base.html' %}

{% block sidebar %}
{% endblock sidebar %}

{% block content %}
    <ul class="exams-grid">
        {% for subject in list_subject %}
            <li class="col-lg-3 col-md-4 col-sm-6">
                <img src="{{ subject.get_image_url }}" alt="" class="img-responsive">
                <div class="description">
                    <h3>{{ subject.name }}</h3>
                    <ul>
                        <li><i class="fa fa-calendar"></i>{{ subject.latest_session.start_date|date:'d/m/Y' }}</li>
                    </ul>
                    <p>{{ subject.description }}.</p>
                </div>
                <a href="{% url 'subjects:detail' subject.pk %}"><span>Detail subject</span></a>
            </li>
        {% endfor %}
    </ul>
{% endblock content %}