ars/blog/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', view=views.BlogView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/$', views.BlogDetailView.as_view(), name='detail'),
]

ars/comments/urls.py
from django.conf.urls import include, url

from . import views


urlpatterns = [
    url(r'^$', view=views.CreateCommentView.as_view(), name='create'),
]

mooc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from ars.subjects.views import ListSubjectView


urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),

    url(r'^$', view=ListSubjectView.as_view(), name='home'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
    
    url(r'^admin/', include('ars.admin.urls', namespace='admin')),
    url(r'^teachers/', include('ars.teachers.urls', namespace='teachers')),
    url(r'^students/', include('ars.students.urls', namespace='students')),
    url(r'^subjects/', include('ars.subjects.urls', namespace='subjects')),
    url(r'^about-us/', include('ars.about.urls', namespace='about')),
    url(r'^contact/', include('ars.contact.urls', namespace='contact')),
    url(r'^blog/', include('ars.blog.urls', namespace='blog')),
    url(r'^category/', include('ars.categories.urls', namespace='category')),
    url(r'^comment/', include('ars.comments.urls', namespace='comment')),
]

ars/blog/models.py
from django.db import models
from django.conf import settings

from ars.teachers.models import Teacher
from ars.core.models import Timestampable

# Create your models here.
class Blog(Timestampable):
    WAITING = 1
    APPROVE = 2

    STATUS_CHOICES = (
        (WAITING, 'Waiting'),
        (APPROVE, 'Approve')
    )

    teacher = models.ForeignKey(Teacher)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField()
    content = models.TextField()
    status = models.SmallIntegerField(choices=STATUS_CHOICES, default=WAITING)
    image = models.ImageField(upload_to=settings.BLOG_DIR, max_length=255, default='', blank=False)

    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Blogs"
        db_table = 'blog'

    def get_image_url(self):
        if self.image:
            return self.image.url
        return ''

    def __str__(self):
        return self.title

ars/blog/views.py
from django.views.generic import ListView, DetailView

from ars.blog.models import Blog
from ars.core.views import BaseView
from ars.comments.models import Comment

# Create your views here.
class BlogView(BaseView, ListView):
    """docstring for BlogView"""
    model = Blog
    context_object_name = "list_blog"
    template_name = 'blog/index.html'
    paginate_by = 5

    def get_queryset(self):
        return Blog.objects.order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(BlogView, self).get_context_data(**kwargs)
        info = {
            'info': {
                'title': 'Blog',
                },
            'page_title': 'Blog',
        }
        context.update(info)
        return context

class BlogDetailView(BaseView, DetailView):
    """docstring for BlogDetailView"""
    model = Blog
    template_name = 'blog/detail.html'

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        info = {
            'info': {
                'title': self.object.title,
                },
            'page_title': 'Blog',
            'comments': Comment.objects.filter(blog=self.object).order_by('-id')
        }
        context.update(info)
        return context
        

templates/blog/detail.html
{% extends 'layout/base.html' %}
{% load staticfiles %}

{% block related_subjects %}
{% endblock related_subjects %}

{% block content %}
    <!-- ==== BLOG START == -->
    <div class="col-sm-8">
        <!-- ==== POST START == -->

        <div class="post row">
            <div class="col-md-12">
                <img src="{{ object.get_image_url }}" alt="" class="img-responsive post-cover" />
                <div class="post-date">
                    <div class="post-day">28</div>
                    <div class="post-month">Sep</div>
                </div>
                <h1>Morbi nec quam sed elit pharetra</h1>
                <div class="meta">
                    <span><i class="fa fa-user"></i><a href="{% url 'teachers:detail' object.teacher.pk %}">{{ object.teacher.username }}</a></span>
                    <span><i class="fa fa-comments"></i><a href="#">{{ object.comments.count }}</a></span>
                </div>
                <p class="intro">
                    {{ object.content|safe }}
                </p>
                
                <p><a href="{% url 'blog:index' %}" class="btn btn-primary">Back</a></p>
            </div>
        </div>

        <!-- ==== POST END == -->

        <!-- ==== COMMENTS START ==== -->
        {% if comments|length > 0%}
            <div class="row">
                <div class="col-sm-12">
                    <h3>Comments</h3>
                    <ul class="media-list">
                        {% for comment in comments %}
                            <li class="media">
                                <a class="pull-left media-photo" href="#"><img class="media-object img-responsive" src="{% static 'frontend/images/comment1.jpg' %}" alt="" /></a>
                                <div class="media-body">
                                    <h5 class="media-heading">{{ comment.profile.user.username }}</h5>
                                    <p class="meta">
                                        <span><i class="fa fa-calendar"></i>{{ comment.create_date|date:'d/m/Y' }}</span>
                                    </p>
                                    <p>{{ comment.content }}.</p>                                    
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        <!-- ==== COMMENTS END ==== -->

        <!-- ==== COMMENT FORM START ==== -->
        {% if user.is_authenticated %}
            <div class="row">
                <div class="col-sm-12" data-scroll-reveal>
                    <hr>
                    <h3>Write a Comment</h3>
                </div>
            </div>
            <form role="form" method="POST" action="{% url 'comment:create' %}">
                {% csrf_token %}
                <input type="hidden" name="blog" value="{{ object.pk }}" />
                <div class="row" data-scroll-reveal>
                    <div class="form-group col-sm-12">
                        <textarea name="content" class="form-control" rows="5"></textarea>
                    </div>
                </div>
                <div class="row" data-scroll-reveal>
                    <div class="form-group col-sm-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        {% endif %}
        <!-- ==== COMMENTS FORM END ==== -->
    </div>
    <!-- ==== BLOG END == -->
{% endblock %}

templates/blog/index.html
{% extends 'layout/base.html' %}
{% load staticfiles %}

{% block related_subjects %}
{% endblock related_subjects %}

{% block content %}
    <!-- ==== BLOG START == -->
    <div class="col-sm-8">
        {% for blog in list_blog %}
            <div class="post row" data-scroll-reveal>
                <div class="col-md-5">
                    <a href="{% url 'blog:detail' blog.pk blog.slug %}"><img src="{{ blog.get_image_url }}" alt="" class="img-responsive" /></a>
                    <div class="post-date">
                        <div class="post-day">{{ blog.create_date|date:'d' }}</div>
                        <div class="post-month">Sep</div>
                    </div>
                </div>
                <div class="col-md-7">
                    <h3><a href="{% url 'blog:detail' blog.pk blog.slug %}">{{ blog.title }}</a></h3>
                    <div class="meta">
                        <span><i class="fa fa-user"></i><a href="{% url 'teachers:detail' blog.teacher.pk %}">{{ blog.teacher.username }}</a></span>
                        <span><i class="fa fa-comments"></i><a href="#">{{ blog.comments.count }}</a></span>
                    </div>
                    <p class="intro">{{ blog.description }}.<br>
                    <a href="#">Read More <i class="fa fa-angle-right"></i></a></p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <hr>
                </div>
            </div>
        {% endfor %}

        <!-- ==== PAGINATION START == -->
        <div data-scroll-reveal-initialized="true" style="-webkit-transform: translatey(0);transform: translatey(0);opacity: 1;-webkit-transition: -webkit-transform 0.66s ease-in-out 0s,  opacity 0.66s ease-in-out 0s;transition: transform 0.66s ease-in-out 0s, opacity 0.66s ease-in-out 0s;-webkit-perspective: 1000;-webkit-backface-visibility: hidden;" class="row" data-scroll-reveal="">
            <div class="col-sm-6">
                {% if page_obj.has_previous %}                        
                    <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary lesson-prev"><i class="fa fa-caret-left"></i> &nbsp; Previous</a>
                {% endif %}
            </div>

            <div class="col-sm-6 text-right">
                {% if page_obj.has_next %}                        
                    <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary lesson-next">Next &nbsp; <i class="fa fa-caret-right"></i></a>                        
                {% endif %}
            </div>
        </div>
        <!-- ==== PAGINATION END == -->
    </div>
    <!-- ==== BLOG END == -->
{% endblock %}